patchedDependencies:
  next-auth@4.24.15: patches/next-auth@4.24.15.patch

overrides:
  '@auth/core': '-'
  next: ^15.5.24
  preact@<10.27.3: ^10.27.3
  postcss@<8.5.23: ^8.5.23
  nanoid@<3.3.18: ^3.3.18
  tar@<7.5.21: ^7.5.21
  glob@>=10.2.0 <10.5.0: ^10.5.0
  node-forge@<1.4.0: ^1.4.0
  rollup@>=4.0.0 <4.59.0: ^4.59.0
  serialize-javascript@<7.0.5: ^7.0.5
  h3@<1.15.9: ^1.15.9
  nitropack@<2.13.4: ^2.13.4
  lodash@<4.18.0: ^4.18.0
  defu@<6.1.5: ^6.1.5
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  js-yaml@>=4.0.0 <4.3.2: ^4.3.2
  minimatch@<3.1.4: ^3.1.4
  minimatch@>=5.0.0 <5.1.8: ^5.1.8
  minimatch@>=9.0.0 <9.0.7: ^9.0.7
  brace-expansion@<1.1.21: ^1.1.21
  brace-expansion@>=2.0.0 <2.1.7: ^2.1.7
  picomatch@<2.3.2: ^2.3.2
  picomatch@>=4.0.0 <4.0.4: ^4.0.4
  ajv@<6.14.0: ^6.14.0
  flatted@<3.4.2: ^3.4.2
  '@humanfs/node@<0.16.8': ^0.16.8

packageExtensions:
  next-auth@4.24.15:
    peerDependenciesMeta:
      next:
        optional: true
      react:
        optional: true
      react-dom:
        optional: true
